#!/bin/bash
#
# I use this script when I login to load all of my program I use :-) 
#

SESSION=$USER

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
  echo "Session $SESSION already exists. Attaching."
  sleep 1
  tmux -2 attach -t $SESSION
  exit 0;
fi

tmux new-session -d -s $SESSION

# Chat window with IRC
tmux new-window -t $SESSION:0 -n 'IRC' 
tmux send-keys -t $SESSION:0.0 'weechat-curses' C-m

# Mail and News with mutt and news
tmux new-window -t $SESSION:1 -n 'Mail/News' 
tmux send-keys -t $SESSION:1.0 'mutt' C-m
tmux split-window -h -t $SESSION:1
tmux send-keys -t $SESSION:1.1 'news' C-m
tmux select-layout even-vertical

# Twitter
tmux new-window -t $SESSION:2 -n 'Twitter'
tmux send-keys -t $SESSION:2.0 'ttytter' C-m

# MSN
tmux new-window -t $SESSION:3 -n 'MSN'
tmux send-keys -t $SESSION:3.0 'centerim' C-m

# Shell
tmux new-window -t $SESSION:4 -n 'Shell'

# Tmux window to start at. 
tmux select-window -t $SESSION:0
tmux -2 attach -t $SESSION
